import {
	chownSync,
	mkdirSync,
	readFileSync,
	rmSync,
	writeFileSync,
} from "node:fs";
import path from "node:path";
import { generalLogger as logger } from "../logger.js";
import { getUser } from "../plugins/auth.plugin.js";

// ---------------------------------------------------------------------------
// Server-side mail filters (Gmail-style) backed by Dovecot Sieve.
//
// The IMAP mail store (docker-mailserver's /var/mail) is bind-mounted into
// this container read-write at MAIL_DATA_DIR. Each account's sieve script
// lives at <domain>/<local>/home/.dovecot.sieve — exactly the path Dovecot's
// active config resolves for `sieve = ~/.dovecot.sieve` (userdb derives
// home=/var/mail/%d/%u/home/). Writing the file is all that's needed: Dovecot
// recompiles on mtime change at the next LMTP delivery.
//
// The mailbox ALWAYS comes from the JWT (verified against IMAP at login) —
// never from client-supplied request data — and is additionally sanitized
// before being used in a path.
// ---------------------------------------------------------------------------

function mailDataDir() {
	// Read lazily (not module scope) so tests can redirect the mail store root.
	return process.env.MAIL_DATA_DIR || "/var/mail";
}

const SIEVE_FILE = ".dovecot.sieve";
const SIEVE_BIN = ".dovecot.svbin";
const SIEVE_LOG = ".dovecot.sieve.log";
const RULES_FILE = ".ezmail-filters.json";

// Split "local@domain" into path-safe halves. Rejects traversal (".."),
// separators and anything outside the charset docker-mailserver account
// names actually use.
export function mailboxParts(mailbox) {
	const at = String(mailbox || "").lastIndexOf("@");
	if (at <= 0 || at === mailbox.length - 1) return null;
	const local = mailbox.slice(0, at);
	const domain = mailbox.slice(at + 1);
	const safe = /^[A-Za-z0-9._-]+$/;
	if (!safe.test(local) || !safe.test(domain)) return null;
	if (local.includes("..") || domain.includes("..")) return null;
	return { local, domain };
}

function homeDir(mailbox) {
	const parts = mailboxParts(mailbox);
	if (!parts) return null;
	return path.join(mailDataDir(), parts.domain, parts.local, "home");
}

export { homeDir };

// Sieve string literal escaping (backslash + double quote).
function sieveEscape(s) {
	return String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

// Dovecot folder names: keep to letters/digits/space/_-./ — flat names for
// v1 (no hierarchy), always safe to embed in a sieve string.
function validFolderName(folder) {
	return /^[A-Za-z0-9][A-Za-z0-9 ._-]*$/.test(folder) && !folder.includes("..");
}

function validRule(rule) {
	if (!rule || typeof rule !== "object") return false;
	if (!["from", "subject", "to"].includes(rule.field)) return false;
	if (!["contains", "is"].includes(rule.match)) return false;
	if (typeof rule.value !== "string" || rule.value.trim().length === 0)
		return false;
	if (rule.value.length > 256) return false;
	return typeof rule.folder === "string" && validFolderName(rule.folder);
}

// Pure generator — exported for tests.
export function generateSieveScript(rules) {
	const lines = [
		'require ["fileinto", "mailbox"];',
		"",
		"# Generated by ezmail — server-side mail filters.",
		"# Applies at LMTP delivery. First matching rule wins.",
		"",
	];
	for (const rule of rules) {
		const v = sieveEscape(rule.value);
		const test =
			rule.field === "from" || rule.field === "to"
				? rule.match === "is"
					? `address :is "${rule.field}" "${v}"`
					: `address :contains "${rule.field}" "${v}"`
				: rule.match === "is"
					? `header :is "Subject" "${v}"`
					: `header :contains "Subject" "${v}"`;
		lines.push(`# ${rule.field} ${rule.match} "${sieveEscape(rule.value)}"`);
		lines.push(`if ${test} {`);
		lines.push(`\tfileinto :create "${sieveEscape(rule.folder)}";`);
		lines.push("\tstop;");
		lines.push("}");
		lines.push("");
	}
	return lines.join("\n");
}

// Validated write: rules array -> JSON sidecar + sieve script. Returns the
// number of rules written. enabled=false removes the sieve script (rules are
// kept so the UI can re-enable later without retyping).
export function writeFilters(mailbox, rules, enabled) {
	const dir = homeDir(mailbox);
	if (!dir) throw new Error("invalid mailbox");
	mkdirSync(dir, { recursive: true });

	const cleanRules = rules.filter(validRule);
	if (cleanRules.length !== rules.length) {
		throw new Error("Invalid filter rule(s)");
	}

	writeFileSync(
		path.join(dir, RULES_FILE),
		JSON.stringify({ enabled: !!enabled, rules: cleanRules }, null, "\t"),
		{ encoding: "utf8", mode: 0o644 },
	);

	const sievePath = path.join(dir, SIEVE_FILE);
	if (enabled && cleanRules.length > 0) {
		writeFileSync(sievePath, generateSieveScript(cleanRules), {
			encoding: "utf8",
			mode: 0o644,
		});
	} else {
		// Disabled or empty: remove script + compiled artifacts so Dovecot
		// falls back to plain delivery.
		for (const f of [SIEVE_FILE, SIEVE_BIN, SIEVE_LOG]) {
			try {
				rmSafe(path.join(dir, f));
			} catch {
				// best effort
			}
		}
	}

	// In production this container runs as root; hand the files to the mail
	// user (docker-mailserver uses uid/gid 5000 "docker"). Local dev ignores
	// failures (non-root cannot chown) — files are 0644 so Dovecot still reads them.
	try {
		chownSync(dir, 5000, 5000);
	} catch {
		// non-root dev environment
	}
	for (const f of [RULES_FILE, SIEVE_FILE]) {
		try {
			chownSync(path.join(dir, f), 5000, 5000);
		} catch {
			// file may not exist (disabled) or non-root — ignore
		}
	}

	logger.info(
		`[FILTERS] wrote ${cleanRules.length} rule(s) for ${mailbox} (enabled=${!!enabled})`,
	);
	return cleanRules.length;
}

function rmSafe(p) {
	try {
		rmSync(p, { force: true });
	} catch {
		// ignore
	}
}

function readFilters(mailbox) {
	const dir = homeDir(mailbox);
	if (!dir) return { enabled: false, rules: [], sieveSource: undefined };
	let state = { enabled: false, rules: [] };
	try {
		const raw = readFileSync(path.join(dir, RULES_FILE), "utf8");
		const parsed = JSON.parse(raw);
		if (Array.isArray(parsed?.rules)) {
			state = {
				enabled: !!parsed.enabled,
				rules: parsed.rules.filter(validRule),
			};
		}
	} catch {
		// no sidecar yet — treat as unconfigured
	}
	let sieveSource;
	if (state.enabled && state.rules.length > 0) {
		try {
			sieveSource = readFileSync(path.join(dir, SIEVE_FILE), "utf8");
		} catch {
			// script missing (e.g. written by hand); report rules without source
		}
	}
	return { ...state, sieveSource };
}

export const FilterService = {
	get: async ({ jwt, cookie, status }) => {
		const user = await getUser(jwt, cookie);
		if (!user?.mailbox || !user?.password)
			return status(401, { success: false, message: "Unauthorized" });
		const state = readFilters(user.mailbox);
		return {
			success: true,
			data: { mailbox: user.mailbox, ...state },
		};
	},

	put: async ({ jwt, cookie, body, status }) => {
		const user = await getUser(jwt, cookie);
		if (!user?.mailbox || !user?.password)
			return status(401, { success: false, message: "Unauthorized" });
		try {
			const ruleCount = writeFilters(user.mailbox, body.rules, body.enabled);
			return {
				success: true,
				data: { ruleCount, enabled: !!body.enabled },
			};
		} catch (err) {
			logger.error(`[FILTERS] 💥 write failed: ${err.message}`);
			return { success: false, message: err.message || "Filter save failed" };
		}
	},

	remove: async ({ jwt, cookie, status }) => {
		const user = await getUser(jwt, cookie);
		if (!user?.mailbox || !user?.password)
			return status(401, { success: false, message: "Unauthorized" });
		const dir = homeDir(user.mailbox);
		if (dir) {
			for (const f of [RULES_FILE, SIEVE_FILE, SIEVE_BIN, SIEVE_LOG]) {
				rmSafe(path.join(dir, f));
			}
			logger.info(`[FILTERS] removed all filters for ${user.mailbox}`);
		}
		return { success: true, data: { removed: true } };
	},
};
